# Generated by Django 5.0.1 on 2024-02-06 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_by', models.CharField(blank=True, max_length=30, null=True)),
                ('video', models.FileField(upload_to='videos', verbose_name='Trec Videos')),
                ('file_name', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.BooleanField(default=False)),
                ('date_uploaded', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(default='cluster_id', on_delete=django.db.models.deletion.CASCADE, to='pages.category')),
            ],
        ),
    ]
