# Generated by Django 5.0.6 on 2025-06-11 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(choices=[('annotation', 'Video Annotation'), ('video_qa', 'Video Question Answering')], default='annotation', max_length=10)),
                ('project_name', models.CharField(max_length=100, unique=True)),
                ('is_link', models.BooleanField(default=False)),
                ('cluster_csv', models.FileField(blank=True, null=True, upload_to='cluster_csv', verbose_name='Trec Videos Cluster Info')),
                ('number_of_annotators', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=250)),
                ('correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answers', to='pages.question')),
            ],
        ),
        migrations.CreateModel(
            name='VideoGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('project_name', models.CharField(default='', max_length=50)),
                ('is_assigned', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_keywords', models.CharField(max_length=150)),
                ('cluster_id', models.IntegerField()),
                ('admin_approved', models.BooleanField(default=False)),
                ('cluster_similarity_score', models.FloatField(default=0.0)),
                ('project', models.ForeignKey(blank=True, default=1374, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.projecttitle')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.videogroup')),
            ],
            options={
                'ordering': ['-cluster_similarity_score'],
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_path', models.CharField(blank=True, max_length=250, null=True)),
                ('youtube_vid_id', models.CharField(blank=True, max_length=50, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('file_name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('keywords', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.BooleanField(blank=True, default=None, null=True)),
                ('video_similarity_score', models.FloatField(default=0.0)),
                ('admin_approve', models.BooleanField(blank=True, default=False, null=True)),
                ('date_uploaded', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_categories', to='pages.category')),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pages.projecttitle')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.question')),
            ],
            options={
                'ordering': ['-video_similarity_score'],
            },
        ),
    ]
