# Generated by Django 5.0.1 on 2024-02-06 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_category_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.category'),
        ),
    ]
