# Generated by Django 5.0.1 on 2024-09-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_category_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='group',
            new_name='cluster_id',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='cluster_keywords',
        ),
        migrations.AddField(
            model_name='videos',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='videos',
            name='keywords',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
