# Generated by Django 5.0.1 on 2024-09-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_rename_group_category_cluster_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='cluster_csv',
            field=models.FileField(blank=True, null=True, upload_to='cluster_csv', verbose_name='Trec Videos Cluster Info'),
        ),
    ]
