# Generated by Django 5.0.1 on 2024-09-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_videos_cluster_csv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cluster_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
