# Generated by Django 5.0.1 on 2024-09-01 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pages', '0009_alter_category_cluster_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='cluster_csv',
        ),
        migrations.AddField(
            model_name='category',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
        migrations.AddField(
            model_name='projecttitle',
            name='cluster_csv',
            field=models.FileField(blank=True, null=True, upload_to='cluster_csv', verbose_name='Trec Videos Cluster Info'),
        ),
    ]
