# Generated by Django 5.0.1 on 2024-09-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_remove_videos_cluster_csv_category_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='number_of_annotators',
        ),
        migrations.AddField(
            model_name='projecttitle',
            name='number_of_annotators',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
