# Generated by Django 5.0.1 on 2024-09-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_remove_videos_number_of_annotators_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cluster_keywords',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='projecttitle',
            name='project_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='videos',
            name='checked_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='file_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='keywords',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
