# Generated by Django 5.0.1 on 2024-09-02 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_annotationgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotationgroup',
            name='user',
        ),
        migrations.AlterField(
            model_name='category',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.annotationgroup'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.annotationgroup'),
        ),
    ]
