# Generated by Django 5.0.1 on 2024-09-02 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pages', '0014_remove_annotationgroup_user_alter_category_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
        migrations.DeleteModel(
            name='AnnotationGroup',
        ),
    ]
