# Generated by Django 5.0.1 on 2024-09-27 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_alter_category_group_alter_videos_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='group',
        ),
        migrations.AddField(
            model_name='projecttitle',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projecttitle',
            name='number_of_annotators',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
