# Generated by Django 5.0.1 on 2024-09-28 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_alter_videos_checked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_categories', to='pages.category'),
        ),
    ]
