# Generated by Django 5.0.1 on 2024-09-29 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_alter_videos_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='admin_approved',
            field=models.BooleanField(default=False),
        ),
    ]
