# Generated by Django 5.0.1 on 2024-10-06 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_category_admin_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='status',
            field=models.BooleanField(default=None),
        ),
    ]
