# Generated by Django 5.0.1 on 2024-10-06 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_alter_videos_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='status',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
