# Generated by Django 5.0.1 on 2024-10-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_alter_videos_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-cluster_similarity_score']},
        ),
        migrations.AlterModelOptions(
            name='videos',
            options={'ordering': ['-video_similarity_score']},
        ),
        migrations.AddField(
            model_name='category',
            name='cluster_similarity_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='videos',
            name='video_similarity_score',
            field=models.FloatField(default=0.0),
        ),
    ]
