# Generated by Django 5.0.1 on 2024-11-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_alter_category_options_alter_videos_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttitle',
            name='project_type',
            field=models.CharField(choices=[('annotation', 'Image Annotation'), ('video_qa', 'Image Question Answering')], default='annotation', max_length=10),
        ),
    ]
