# Generated by Django 5.0.1 on 2024-11-10 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_projecttitle_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='project',
            field=models.ForeignKey(blank=True, default=1374, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.projecttitle'),
        ),
    ]
