# Generated by Django 5.0.1 on 2024-11-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_answer_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=250),
        ),
    ]
