# Generated by Django 5.0.1 on 2024-11-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_alter_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='admin_approve',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
