# Generated by Django 5.0.1 on 2025-01-12 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_videos_admin_approve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttitle',
            name='project_type',
            field=models.CharField(choices=[('annotation', 'Video Annotation'), ('video_qa', 'Video Question Answering')], default='annotation', max_length=10),
        ),
    ]
