# Generated by Django 5.0.1 on 2025-01-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_alter_projecttitle_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttitle',
            name='project_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
