# Generated by Django 5.0.1 on 2025-01-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_videogroup_alter_category_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogroup',
            name='project_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
