# Generated by Django 5.0.1 on 2025-01-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0035_videogroup_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='video',
        ),
        migrations.AddField(
            model_name='videos',
            name='video_path',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
