# Generated by Django 5.0.1 on 2025-01-31 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0036_remove_videos_video_videos_video_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='youtube_vid_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
