# Generated by Django 5.0.1 on 2025-02-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0037_videos_youtube_vid_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
