# Generated by Django 5.0.1 on 2025-03-09 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0038_videos_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttitle',
            name='is_link',
            field=models.BooleanField(default=False),
        ),
    ]
