# Generated by Django 5.0.1 on 2025-03-16 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0039_projecttitle_is_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='video_path',
            field=models.CharField(max_length=250),
        ),
    ]
