# Generated by Django 5.0.1 on 2025-03-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0040_alter_videos_video_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=models.CharField(max_length=250)),
        ),
    ]
