# Generated by Django 5.0.1 on 2025-03-16 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0041_videos_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='video',
        ),
    ]
