# Generated by Django 5.0.1 on 2026-01-30 01:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0042_remove_videos_video'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['question', '-correct', 'id'], 'verbose_name': 'Answer', 'verbose_name_plural': 'Answers'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-cluster_similarity_score'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='projecttitle',
            options={'ordering': ['-created_at'], 'verbose_name': 'Project Title', 'verbose_name_plural': 'Project Titles'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_at'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='videogroup',
            options={'ordering': ['project_name', 'name'], 'verbose_name': 'Video Group', 'verbose_name_plural': 'Video Groups'},
        ),
        migrations.AlterModelOptions(
            name='videos',
            options={'ordering': ['-video_similarity_score', 'id'], 'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
        migrations.AddField(
            model_name='answer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='projecttitle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='projecttitle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='videogroup',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='videos',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='answer',
            name='correct',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='admin_approved',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='cluster_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='cluster_keywords',
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='category',
            name='cluster_similarity_score',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='category',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='pages.videogroup'),
        ),
        migrations.AlterField(
            model_name='category',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='pages.projecttitle'),
        ),
        migrations.AlterField(
            model_name='projecttitle',
            name='number_of_annotators',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='projecttitle',
            name='project_name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='projecttitle',
            name='project_type',
            field=models.CharField(choices=[('annotation', 'Video Annotation'), ('video_qa', 'Video Question Answering')], db_index=True, default='annotation', max_length=10),
        ),
        migrations.AlterField(
            model_name='projecttitle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='videogroup',
            name='is_assigned',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='videogroup',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='videogroup',
            name='project_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='videogroup',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='videos',
            name='admin_approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='videos',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='videos',
            name='date_uploaded',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='file_name',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='pages.projecttitle'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='pages.question'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='status',
            field=models.BooleanField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='video_path',
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='videos',
            name='video_similarity_score',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='videos',
            name='youtube_vid_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['cluster_keywords', 'project'], name='pages_categ_cluster_090f4f_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['group', 'admin_approved'], name='pages_categ_group_i_4f11a3_idx'),
        ),
        migrations.AddIndex(
            model_name='videos',
            index=models.Index(fields=['project', 'status', 'is_available'], name='pages_video_project_64f71f_idx'),
        ),
        migrations.AddIndex(
            model_name='videos',
            index=models.Index(fields=['category', 'is_available'], name='pages_video_categor_ac2898_idx'),
        ),
        migrations.AddIndex(
            model_name='videos',
            index=models.Index(fields=['checked_by', 'status'], name='pages_video_checked_e658a9_idx'),
        ),
    ]
