# Generated by Django 5.0.6 on 2025-06-11 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Userreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(choices=[('annotation', 'Video Annotation'), ('video_qa', 'Video Question Answering')], default='annotation', max_length=10)),
                ('project_name', models.CharField(default='', max_length=50)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('finished_job', models.BooleanField(default=False)),
                ('admin_approved', models.BooleanField(default=False)),
                ('is_job_admin', models.BooleanField(default=False)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='userregs', to='pages.videogroup')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.projecttitle')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userreg', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
