# Generated by Django 5.0.1 on 2024-09-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreg',
            name='finished_job',
            field=models.BooleanField(default=False),
        ),
    ]
