# Generated by Django 5.0.1 on 2024-09-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_userreg_finished_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreg',
            name='admin_approved',
            field=models.BooleanField(default=False),
        ),
    ]
