# Generated by Django 5.0.1 on 2024-11-20 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_question_answer_videos_question'),
        ('registration', '0003_userreg_admin_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreg',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.projecttitle'),
        ),
    ]
