# Generated by Django 5.0.1 on 2024-11-20 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_userreg_is_job_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreg',
            name='is_job_admin',
        ),
    ]
