# Generated by Django 5.0.1 on 2025-01-13 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_remove_userreg_is_job_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreg',
            name='title',
        ),
        migrations.AddField(
            model_name='userreg',
            name='project_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
