# Generated by Django 5.0.1 on 2025-01-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_remove_userreg_title_userreg_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreg',
            name='is_job_admin',
            field=models.BooleanField(default=False),
        ),
    ]
