# Generated by Django 5.0.1 on 2025-01-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_videogroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videogroup',
            name='project',
        ),
        migrations.AddField(
            model_name='videogroup',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
