# Generated by Django 5.0.1 on 2025-01-19 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_remove_videogroup_project_videogroup_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreg',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='registration.videogroup'),
        ),
    ]
