# Generated by Django 5.0.1 on 2025-01-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_alter_userreg_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreg',
            name='project_type',
            field=models.CharField(choices=[('annotation', 'Video Annotation'), ('video_qa', 'Video Question Answering')], default='annotation', max_length=10),
        ),
    ]
