# Generated by Django 5.0.1 on 2025-01-19 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_videogroup_alter_category_group'),
        ('registration', '0013_userreg_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreg',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.videogroup'),
        ),
        migrations.DeleteModel(
            name='VideoGroup',
        ),
    ]
