# Generated by Django 5.0.1 on 2025-01-20 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0035_videogroup_user'),
        ('registration', '0014_alter_userreg_group_delete_videogroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreg',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='userregs', to='pages.videogroup'),
        ),
    ]
